[build]
builder = "NIXPACKS"
buildCommand = "cd cms && npm ci --legacy-peer-deps && npm run build"

[deploy]
startCommand = "cd cms && npm run serve"
healthcheckPath = "/api/products"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
